public class VariablesTheme {

    public static void main(String[] args) {
        System.out.println("1. Создание переменных и вывод их значений на консоль.");
        byte gpu = 4;
        short ram = 16;
        int maxPowerGPU = 85;
        long ssdVolume = 512;
        float cpuFrequence = 3.3f;
        double osBuild = 22000.795d;
        char audio = 'R';
        boolean isGaming = true;
        System.out.println("Операционная система: Windows 11 сборки " + osBuild);
        System.out.println("Процессор: AMD Ryzen 5 5600H " + cpuFrequence + "GHz");
        System.out.println("Накопитель: SSD SAMSUNG_MZALQ512 " + ssdVolume + "GB");
        System.out.println("Оперативная память: " + ram + "GB");
        System.out.println("Видеокарта: NVIDIA GeForce RTX 3050 Laptop GPU " + gpu + "GB");
        System.out.println("Максимальное энергопотребление видеокарты: " + maxPowerGPU + "W");
        System.out.println("Звуковая карта: Realtek(" + audio + ")");
        System.out.println("Игровой копьютер: " + isGaming);
        System.out.println("\n2. Расчёт стоимости товара со скидкой.");
        double priceX = 100;
        double priceY = 200;
        double discountAmount = (priceX + priceY)* 0.11;
        System.out.println("Сумма скидки = " + discountAmount);
        System.out.println("Стоимость товаров, с учётом скидки = " + (priceX + priceY - discountAmount));
        System.out.println("\n3. Вывод на консоль слова JAVA.");
        System.out.println("   J    a  v     v  a");
        System.out.println("   J   a a  v   v  a a");
        System.out.println("J  J  aaaaa  V V  aaaaa");
        System.out.println(" JJ  a     a  V  a     a");
        System.out.println("\n4. Отображение min и max значений числовых типов данных.");
        byte bmax = 127;
        short smax = 32767;
        int imax = 2147483647;
        long lmax = 9223372036854775807l;
        System.out.println("Первоначальное значение 'byte': " + bmax);
        System.out.println("Значение 'byte' после инкремента: " + ++bmax);
        System.out.println("Значение 'byte' после декремента: " + --bmax);
        System.out.println("Первоначальное значение 'short': " + smax);
        System.out.println("Значение 'short' после инкремента: " + ++smax);
        System.out.println("Значение 'short' после декремента: " + --smax);
        System.out.println("Первоначальное значение 'int': " + imax);
        System.out.println("Значение 'int' после инкремента: " + ++imax);
        System.out.println("Значение 'int' после декремента: " + --imax);
        System.out.println("Первоначальное значение 'long': " + lmax);
        System.out.println("Значение 'long' после инкремента: " + ++lmax);
        System.out.println("Значение 'long' после декремента: " + --lmax);
        System.out.println("\n5. Перестановка значений переменных.");
        System.out.println("Перестановка значений переменных с помощью третьей переменной:");
        int one = 1;
        int two = 2;
        int temp;
        System.out.println("Первоначальное значение первой переменной: " + one);
        System.out.println("Первоначальное значение второй переменной: " + two);
        temp = one;
        one = two;
        two = temp;
        System.out.println("Значение первой переменной после перестановки: " + one);
        System.out.println("Значение второй переменной после перестановки: " + two);
        System.out.println("Перестановка значений переменных с помощью арифимитический действий:");
        two = two + one;
        one = two - one;
        two = two - one;
        System.out.println("Значение первой переменной после перестановки: " + one);
        System.out.println("Значение второй переменной после перестановки: " + two);
        System.out.println("Перестановка значений переменных с помощью побитовой операции:");
        one = one ^ two;
        two = one ^ two;
        one = one ^ two;
        System.out.println("Значение первой переменной после перестановки: " + one);
        System.out.println("Значение второй переменной после перестановки: " + two);
        System.out.println("\n6. Вывод символов и их кодов.");
        int thirtyfive = 35;
        int thirtyeigth = 38;
        int sixtyfour = 64;
        int ninetyfour = 94;
        int ninetyfive = 95;
        char hash = (char)thirtyfive;
        char ampersand = (char)thirtyeigth;
        char at = (char)sixtyfour;
        char caret = (char)ninetyfour;
        char underscore = (char)ninetyfive;
        System.out.println(thirtyfive + " = " + hash);
        System.out.println(thirtyeigth + " = " + ampersand);
        System.out.println(sixtyfour + " = " + at);
        System.out.println(ninetyfour + " = " + caret);
        System.out.println(ninetyfive + " = " + underscore);
        System.out.println("\n7. Произведение и сумма цифр числа.");
        int number = 345;
        int current = number % 10;
        int sum = 0;
        int multiplier = 0;
        sum = sum + current;
        multiplier = multiplier + current;
        number = number / 10;
        current = number % 10;
        number = number / 10;
        sum = sum + current + number;
        System.out.println("Сумма цифр числа 345 = " + sum);
        multiplier = multiplier * current * number;
        System.out.println("Произведение цифр числа 345 = " + multiplier);
        System.out.println("\n8 Вывод на консоль ASCII-арт Дюка.");
        char backSlash = (char)92;
        char forwardSlash = (char)47;
        char space = (char)32;
        char parenthesisClose = (char)41;
        char parenthesisOpen = (char)40;
        System.out.println("" + space + space + space + space + forwardSlash + backSlash);
        System.out.println("" + space + space + space + forwardSlash + space + space + backSlash);
        System.out.println("" + space + space + forwardSlash + underscore + parenthesisOpen + space + parenthesisClose + backSlash);
        System.out.println("" + space + forwardSlash + space + space + space + space + space + space + backSlash);
        System.out.println("" + forwardSlash + underscore + underscore + underscore + underscore + forwardSlash + backSlash + underscore + underscore + backSlash);
        System.out.println("\n9 Преобразование секунд.");
        int totalSec = 86399;
        int sec = totalSec % 60;
        int min = (totalSec % 3600) / 60;
        int hour = totalSec / 3600;
        System.out.println(hour + ":" + min + ":" + sec);
    }
}